package engine

// GuaInfo 卦象数据
type GuaInfo struct {
	ID       int    // 1-64 (序卦传顺序)
	Name     string // 卦名（如 "乾为天"）
	Symbol   string // 卦符（六爻 Unicode）
	ShangGua string // 上卦名
	XiaGua   string // 下卦名
	YaoDesc  string // 六爻阴阳描述，索引0=初爻, 索引5=上爻 (1=阳, 0=阴)
	GuaCi    string // 卦辞
	XiangCi  string // 象辞
}

// AllGua 64卦数据，按序卦传顺序排列
var AllGua = []GuaInfo{
	{ID: 1, Name: "乾为天", Symbol: "䷀", ShangGua: "乾", XiaGua: "乾", YaoDesc: "111111",
		GuaCi: "元亨利贞", XiangCi: "天行健，君子以自强不息"},
	{ID: 2, Name: "坤为地", Symbol: "䷁", ShangGua: "坤", XiaGua: "坤", YaoDesc: "000000",
		GuaCi: "元亨，利牝马之贞。君子有攸往，先迷后得主，利。西南得朋，东北丧朋。安贞吉",
		XiangCi: "地势坤，君子以厚德载物"},
	{ID: 3, Name: "水雷屯", Symbol: "䷂", ShangGua: "坎", XiaGua: "震", YaoDesc: "010001",
		GuaCi: "元亨利贞。勿用有攸往，利建侯", XiangCi: "云雷屯，君子以经纶"},
	{ID: 4, Name: "山水蒙", Symbol: "䷃", ShangGua: "艮", XiaGua: "坎", YaoDesc: "100010",
		GuaCi: "亨。匪我求童蒙，童蒙求我。初筮告，再三渎，渎则不告。利贞",
		XiangCi: "山下出泉，蒙。君子以果行育德"},
	{ID: 5, Name: "水天需", Symbol: "䷄", ShangGua: "坎", XiaGua: "乾", YaoDesc: "010111",
		GuaCi: "有孚，光亨，贞吉。利涉大川", XiangCi: "云上于天，需。君子以饮食宴乐"},
	{ID: 6, Name: "天水讼", Symbol: "䷅", ShangGua: "乾", XiaGua: "坎", YaoDesc: "111010",
		GuaCi: "有孚窒惕，中吉，终凶。利见大人，不利涉大川",
		XiangCi: "天与水违行，讼。君子以作事谋始"},
	{ID: 7, Name: "地水师", Symbol: "䷆", ShangGua: "坤", XiaGua: "坎", YaoDesc: "000010",
		GuaCi: "贞，丈人吉，无咎", XiangCi: "地中有水，师。君子以容民畜众"},
	{ID: 8, Name: "水地比", Symbol: "䷇", ShangGua: "坎", XiaGua: "坤", YaoDesc: "010000",
		GuaCi: "吉。原筮，元永贞，无咎。不宁方来，后夫凶",
		XiangCi: "地上有水，比。先王以建万国，亲诸侯"},
	{ID: 9, Name: "风天小畜", Symbol: "䷈", ShangGua: "巽", XiaGua: "乾", YaoDesc: "110111",
		GuaCi: "亨。密云不雨，自我西郊", XiangCi: "风行天上，小畜。君子以懿文德"},
	{ID: 10, Name: "天泽履", Symbol: "䷉", ShangGua: "乾", XiaGua: "兑", YaoDesc: "111011",
		GuaCi: "履虎尾，不咥人，亨", XiangCi: "上天下泽，履。君子以辨上下，定民志"},
	{ID: 11, Name: "地天泰", Symbol: "䷊", ShangGua: "坤", XiaGua: "乾", YaoDesc: "000111",
		GuaCi: "小往大来，吉亨", XiangCi: "天地交，泰。后以财成天地之道，辅相天地之宜，以左右民"},
	{ID: 12, Name: "天地否", Symbol: "䷋", ShangGua: "乾", XiaGua: "坤", YaoDesc: "111000",
		GuaCi: "否之匪人，不利君子贞。大往小来", XiangCi: "天地不交，否。君子以俭德辟难，不可荣以禄"},
	{ID: 13, Name: "天火同人", Symbol: "䷌", ShangGua: "乾", XiaGua: "离", YaoDesc: "111101",
		GuaCi: "同人于野，亨。利涉大川，利君子贞", XiangCi: "天与火，同人。君子以类族辨物"},
	{ID: 14, Name: "火天大有", Symbol: "䷍", ShangGua: "离", XiaGua: "乾", YaoDesc: "101111",
		GuaCi: "元亨", XiangCi: "火在天上，大有。君子以遏恶扬善，顺天休命"},
	{ID: 15, Name: "地山谦", Symbol: "䷎", ShangGua: "坤", XiaGua: "艮", YaoDesc: "000100",
		GuaCi: "亨，君子有终", XiangCi: "地中有山，谦。君子以裒多益寡，称物平施"},
	{ID: 16, Name: "雷地豫", Symbol: "䷏", ShangGua: "震", XiaGua: "坤", YaoDesc: "001000",
		GuaCi: "利建侯行师", XiangCi: "雷出地奋，豫。先王以作乐崇德，殷荐之上帝，以配祖考"},
	{ID: 17, Name: "泽雷随", Symbol: "䷐", ShangGua: "兑", XiaGua: "震", YaoDesc: "011001",
		GuaCi: "元亨利贞，无咎", XiangCi: "泽中有雷，随。君子以向晦入宴息"},
	{ID: 18, Name: "山风蛊", Symbol: "䷑", ShangGua: "艮", XiaGua: "巽", YaoDesc: "100110",
		GuaCi: "元亨，利涉大川。先甲三日，后甲三日",
		XiangCi: "山下有风，蛊。君子以振民育德"},
	{ID: 19, Name: "地泽临", Symbol: "䷒", ShangGua: "坤", XiaGua: "兑", YaoDesc: "000011",
		GuaCi: "元亨利贞。至于八月有凶", XiangCi: "泽上有地，临。君子以教思无穷，容保民无疆"},
	{ID: 20, Name: "风地观", Symbol: "䷓", ShangGua: "巽", XiaGua: "坤", YaoDesc: "110000",
		GuaCi: "盥而不荐，有孚颙若", XiangCi: "风行地上，观。先王以省方观民设教"},
	{ID: 21, Name: "火雷噬嗑", Symbol: "䷔", ShangGua: "离", XiaGua: "震", YaoDesc: "101001",
		GuaCi: "亨，利用狱", XiangCi: "雷电噬嗑。先王以明罚敕法"},
	{ID: 22, Name: "山火贲", Symbol: "䷕", ShangGua: "艮", XiaGua: "离", YaoDesc: "100101",
		GuaCi: "亨。小利有攸往", XiangCi: "山下有火，贲。君子以明庶政，无敢折狱"},
	{ID: 23, Name: "山地剥", Symbol: "䷖", ShangGua: "艮", XiaGua: "坤", YaoDesc: "100000",
		GuaCi: "不利有攸往", XiangCi: "山附于地，剥。上以厚下安宅"},
	{ID: 24, Name: "地雷复", Symbol: "䷗", ShangGua: "坤", XiaGua: "震", YaoDesc: "000001",
		GuaCi: "亨。出入无疾，朋来无咎。反复其道，七日来复，利有攸往",
		XiangCi: "雷在地中，复。先王以至日闭关，商旅不行，后不省方"},
	{ID: 25, Name: "天雷无妄", Symbol: "䷘", ShangGua: "乾", XiaGua: "震", YaoDesc: "111001",
		GuaCi: "元亨利贞。其匪正有眚，不利有攸往",
		XiangCi: "天下雷行，物与无妄。先王以茂对时育万物"},
	{ID: 26, Name: "山天大畜", Symbol: "䷙", ShangGua: "艮", XiaGua: "乾", YaoDesc: "100111",
		GuaCi: "利贞。不家食吉，利涉大川", XiangCi: "天在山中，大畜。君子以多识前言往行，以畜其德"},
	{ID: 27, Name: "山雷颐", Symbol: "䷚", ShangGua: "艮", XiaGua: "震", YaoDesc: "100001",
		GuaCi: "贞吉。观颐，自求口实", XiangCi: "山下有雷，颐。君子以慎言语，节饮食"},
	{ID: 28, Name: "泽风大过", Symbol: "䷛", ShangGua: "兑", XiaGua: "巽", YaoDesc: "011110",
		GuaCi: "栋桡，利有攸往，亨", XiangCi: "泽灭木，大过。君子以独立不惧，遁世无闷"},
	{ID: 29, Name: "坎为水", Symbol: "䷜", ShangGua: "坎", XiaGua: "坎", YaoDesc: "010010",
		GuaCi: "习坎，有孚，维心亨，行有尚", XiangCi: "水洊至，习坎。君子以常德行，习教事"},
	{ID: 30, Name: "离为火", Symbol: "䷝", ShangGua: "离", XiaGua: "离", YaoDesc: "101101",
		GuaCi: "利贞，亨。畜牝牛，吉", XiangCi: "明两作，离。大人以继明照于四方"},
	{ID: 31, Name: "泽山咸", Symbol: "䷞", ShangGua: "兑", XiaGua: "艮", YaoDesc: "011100",
		GuaCi: "亨，利贞。取女吉", XiangCi: "山上有泽，咸。君子以虚受人"},
	{ID: 32, Name: "雷风恒", Symbol: "䷟", ShangGua: "震", XiaGua: "巽", YaoDesc: "001110",
		GuaCi: "亨，无咎，利贞，利有攸往", XiangCi: "雷风，恒。君子以立不易方"},
	{ID: 33, Name: "天山遁", Symbol: "䷠", ShangGua: "乾", XiaGua: "艮", YaoDesc: "111100",
		GuaCi: "亨，小利贞", XiangCi: "天下有山，遁。君子以远小人，不恶而严"},
	{ID: 34, Name: "雷天大壮", Symbol: "䷡", ShangGua: "震", XiaGua: "乾", YaoDesc: "001111",
		GuaCi: "利贞", XiangCi: "雷在天上，大壮。君子以非礼弗履"},
	{ID: 35, Name: "火地晋", Symbol: "䷢", ShangGua: "离", XiaGua: "坤", YaoDesc: "101000",
		GuaCi: "康侯用锡马蕃庶，昼日三接", XiangCi: "明出地上，晋。君子以自昭明德"},
	{ID: 36, Name: "地火明夷", Symbol: "䷣", ShangGua: "坤", XiaGua: "离", YaoDesc: "000101",
		GuaCi: "利艰贞", XiangCi: "明入地中，明夷。君子以莅众，用晦而明"},
	{ID: 37, Name: "风火家人", Symbol: "䷤", ShangGua: "巽", XiaGua: "离", YaoDesc: "110101",
		GuaCi: "利女贞", XiangCi: "风自火出，家人。君子以言有物而行有恒"},
	{ID: 38, Name: "火泽睽", Symbol: "䷥", ShangGua: "离", XiaGua: "兑", YaoDesc: "101011",
		GuaCi: "小事吉", XiangCi: "上火下泽，睽。君子以同而异"},
	{ID: 39, Name: "水山蹇", Symbol: "䷦", ShangGua: "坎", XiaGua: "艮", YaoDesc: "010100",
		GuaCi: "利西南，不利东北。利见大人，贞吉",
		XiangCi: "山上有水，蹇。君子以反身修德"},
	{ID: 40, Name: "雷水解", Symbol: "䷧", ShangGua: "震", XiaGua: "坎", YaoDesc: "001010",
		GuaCi: "利西南。无所往，其来复吉。有攸往，夙吉",
		XiangCi: "雷雨作，解。君子以赦过宥罪"},
	{ID: 41, Name: "山泽损", Symbol: "䷨", ShangGua: "艮", XiaGua: "兑", YaoDesc: "100011",
		GuaCi: "有孚，元吉，无咎，可贞，利有攸往。曷之用？二簋可用享",
		XiangCi: "山下有泽，损。君子以惩忿窒欲"},
	{ID: 42, Name: "风雷益", Symbol: "䷩", ShangGua: "巽", XiaGua: "震", YaoDesc: "110001",
		GuaCi: "利有攸往，利涉大川", XiangCi: "风雷，益。君子以见善则迁，有过则改"},
	{ID: 43, Name: "泽天夬", Symbol: "䷪", ShangGua: "兑", XiaGua: "乾", YaoDesc: "011111",
		GuaCi: "扬于王庭，孚号有厉。告自邑，不利即戎，利有攸往",
		XiangCi: "泽上于天，夬。君子以施禄及下，居德则忌"},
	{ID: 44, Name: "天风姤", Symbol: "䷫", ShangGua: "乾", XiaGua: "巽", YaoDesc: "111110",
		GuaCi: "女壮，勿用取女", XiangCi: "天下有风，姤。后以施命诰四方"},
	{ID: 45, Name: "泽地萃", Symbol: "䷬", ShangGua: "兑", XiaGua: "坤", YaoDesc: "011000",
		GuaCi: "亨。王假有庙。利见大人，亨，利贞。用大牲吉，利有攸往",
		XiangCi: "泽上于地，萃。君子以除戎器，戒不虞"},
	{ID: 46, Name: "地风升", Symbol: "䷭", ShangGua: "坤", XiaGua: "巽", YaoDesc: "000110",
		GuaCi: "元亨，用见大人，勿恤，南征吉", XiangCi: "地中生木，升。君子以顺德，积小以高大"},
	{ID: 47, Name: "泽水困", Symbol: "䷮", ShangGua: "兑", XiaGua: "坎", YaoDesc: "011010",
		GuaCi: "亨，贞，大人吉，无咎。有言不信", XiangCi: "泽无水，困。君子以致命遂志"},
	{ID: 48, Name: "水风井", Symbol: "䷯", ShangGua: "坎", XiaGua: "巽", YaoDesc: "010110",
		GuaCi: "改邑不改井，无丧无得，往来井井。汔至亦未繘井，羸其瓶，凶",
		XiangCi: "木上有水，井。君子以劳民劝相"},
	{ID: 49, Name: "泽火革", Symbol: "䷰", ShangGua: "兑", XiaGua: "离", YaoDesc: "011101",
		GuaCi: "巳日乃孚，元亨利贞，悔亡", XiangCi: "泽中有火，革。君子以治历明时"},
	{ID: 50, Name: "火风鼎", Symbol: "䷱", ShangGua: "离", XiaGua: "巽", YaoDesc: "101110",
		GuaCi: "元吉，亨", XiangCi: "木上有火，鼎。君子以正位凝命"},
	{ID: 51, Name: "震为雷", Symbol: "䷲", ShangGua: "震", XiaGua: "震", YaoDesc: "001001",
		GuaCi: "亨。震来虩虩，笑言哑哑。震惊百里，不丧匕鬯",
		XiangCi: "洊雷，震。君子以恐惧修省"},
	{ID: 52, Name: "艮为山", Symbol: "䷳", ShangGua: "艮", XiaGua: "艮", YaoDesc: "100100",
		GuaCi: "艮其背，不获其身。行其庭，不见其人。无咎",
		XiangCi: "兼山，艮。君子以思不出其位"},
	{ID: 53, Name: "风山渐", Symbol: "䷴", ShangGua: "巽", XiaGua: "艮", YaoDesc: "110100",
		GuaCi: "女归吉，利贞", XiangCi: "山上有木，渐。君子以居贤德善俗"},
	{ID: 54, Name: "雷泽归妹", Symbol: "䷵", ShangGua: "震", XiaGua: "兑", YaoDesc: "001011",
		GuaCi: "征凶，无攸利", XiangCi: "泽上有雷，归妹。君子以永终知敝"},
	{ID: 55, Name: "雷火丰", Symbol: "䷶", ShangGua: "震", XiaGua: "离", YaoDesc: "001101",
		GuaCi: "亨，王假之。勿忧，宜日中", XiangCi: "雷电皆至，丰。君子以折狱致刑"},
	{ID: 56, Name: "火山旅", Symbol: "䷷", ShangGua: "离", XiaGua: "艮", YaoDesc: "101100",
		GuaCi: "小亨，旅贞吉", XiangCi: "山上有火，旅。君子以明慎用刑而不留狱"},
	{ID: 57, Name: "巽为风", Symbol: "䷸", ShangGua: "巽", XiaGua: "巽", YaoDesc: "110110",
		GuaCi: "小亨，利有攸往，利见大人", XiangCi: "随风，巽。君子以申命行事"},
	{ID: 58, Name: "兑为泽", Symbol: "䷹", ShangGua: "兑", XiaGua: "兑", YaoDesc: "011011",
		GuaCi: "亨，利贞", XiangCi: "丽泽，兑。君子以朋友讲习"},
	{ID: 59, Name: "风水涣", Symbol: "䷺", ShangGua: "巽", XiaGua: "坎", YaoDesc: "110010",
		GuaCi: "亨。王假有庙，利涉大川，利贞",
		XiangCi: "风行水上，涣。先王以享于帝立庙"},
	{ID: 60, Name: "水泽节", Symbol: "䷻", ShangGua: "坎", XiaGua: "兑", YaoDesc: "010011",
		GuaCi: "亨。苦节不可贞", XiangCi: "泽上有水，节。君子以制数度，议德行"},
	{ID: 61, Name: "风泽中孚", Symbol: "䷼", ShangGua: "巽", XiaGua: "兑", YaoDesc: "110011",
		GuaCi: "豚鱼吉，利涉大川，利贞", XiangCi: "泽上有风，中孚。君子以议狱缓死"},
	{ID: 62, Name: "雷山小过", Symbol: "䷽", ShangGua: "震", XiaGua: "艮", YaoDesc: "001100",
		GuaCi: "亨，利贞。可小事，不可大事。飞鸟遗之音，不宜上宜下，大吉",
		XiangCi: "山上有雷，小过。君子以行过乎恭，丧过乎哀，用过乎俭"},
	{ID: 63, Name: "水火既济", Symbol: "䷾", ShangGua: "坎", XiaGua: "离", YaoDesc: "010101",
		GuaCi: "亨小，利贞。初吉终乱", XiangCi: "水在火上，既济。君子以思患而豫防之"},
	{ID: 64, Name: "火水未济", Symbol: "䷿", ShangGua: "离", XiaGua: "坎", YaoDesc: "101010",
		GuaCi: "亨。小狐汔济，濡其尾，无攸利", XiangCi: "火在水上，未济。君子以慎辨物居方"},
}

// FindGuaByYaoPattern 根据六爻阴阳模式查找卦象
// pattern: 6字符，索引0=初爻(下)，索引5=上爻(上)，'1'=阳 '0'=阴
func FindGuaByYaoPattern(pattern string) *GuaInfo {
	for i := range AllGua {
		if AllGua[i].YaoDesc == pattern {
			return &AllGua[i]
		}
	}
	return nil
}
