package llm

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"regexp"
	"strings"
	"time"
)

// Config 单个 LLM provider 配置
type Config struct {
	APIKey   string
	Endpoint string
	Model    string
}

// Client 通用 LLM 客户端（OpenAI 兼容接口）
type Client struct {
	cfg        Config
	client     *http.Client
	mockDivine func(prompt string) (string, error) // 测试注入
}

// New 创建 LLM 客户端
func New(cfg Config) *Client {
	return &Client{
		cfg:    cfg,
		client: &http.Client{Timeout: 60 * time.Second},
	}
}

// ModelName 返回当前模型名
func (c *Client) ModelName() string {
	return c.cfg.Model
}

type chatReq struct {
	Model    string    `json:"model"`
	Messages []message `json:"messages"`
}

type message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type chatResp struct {
	Choices []struct {
		Message struct {
			Content string `json:"content"`
		} `json:"message"`
	} `json:"choices"`
}

// chatURL 返回 chat/completions 端点 URL
func (c *Client) chatURL() string {
	base := strings.TrimRight(c.cfg.Endpoint, "/")
	if strings.HasSuffix(base, "/chat/completions") {
		return base
	}
	return base + "/chat/completions"
}

// Divine 调用 LLM 解卦
func (c *Client) Divine(prompt string) (string, error) {
	if c.mockDivine != nil {
		return c.mockDivine(prompt)
	}

	body, _ := json.Marshal(chatReq{
		Model: c.cfg.Model,
		Messages: []message{
			{Role: "user", Content: prompt},
		},
	})

	req, err := http.NewRequest("POST", c.chatURL(), bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("创建请求失败: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+c.cfg.APIKey)
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.client.Do(req)
	if err != nil {
		return "", fmt.Errorf("LLM请求失败: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("LLM返回错误: %d", resp.StatusCode)
	}

	var cr chatResp
	if err := json.NewDecoder(resp.Body).Decode(&cr); err != nil {
		return "", fmt.Errorf("LLM响应解析失败: %w", err)
	}
	if len(cr.Choices) == 0 {
		return "", fmt.Errorf("LLM无有效响应")
	}
	return cr.Choices[0].Message.Content, nil
}

// BuildPrompt 构建解卦 prompt，lang 为 "zh" 或 "en"
func BuildPrompt(question, primary, changing, yaoPositions, lang string) string {
	if lang == "en" {
		return fmt.Sprintf(
			"You are a professional I Ching divination reader. Provide a reading for the user's question: \"%s\".\n"+
				"Primary hexagram: %s, Changed hexagram: %s, Changing lines: %s\n\n"+
				"Output strictly in the following structure. Do NOT add any preface, epilogue, or disclaimer:\n\n"+
				"## Primary Hexagram\n"+
				"(Interpretation of the primary hexagram in the context of the question)\n\n"+
				"## Changing Lines\n"+
				"(Insights from the changing lines)\n\n"+
				"## Changed Hexagram\n"+
				"(What the changed hexagram reveals about the future trend)\n\n"+
				"## Overall Advice\n"+
				"(Practical advice combining all aspects)\n\n"+
				"> Write in clear, accessible English. Include Chinese hexagram names with English explanations.\n"+
				"> Be objective — do not add unnecessary emotional flattery. The final advice may offer appropriate encouragement.\n"+
				"[RULES] Do NOT mention your model name, company name, or who generated this.\n"+
				"Do NOT output any disclaimer (e.g. \"This content was generated by AI, for reference only\").\n"+
				"Do NOT start with acknowledgments like \"Sure!\" or \"Here is your reading\". Jump straight into the content.",
			question, primary, changing, yaoPositions,
		)
	}
	return fmt.Sprintf(
		"你是一位专业的易经解卦师。请结合用户问题「%s」和卦象进行分析：\n"+
			"本卦：%s，变卦：%s，变爻：%s\n\n"+
			"请严格按以下结构输出，不要添加任何前言、后记或免责声明：\n"+
			"## 本卦解义\n"+
			"（对本卦的解读，可使用**加粗**突出关键概念）\n\n"+
			"## 变爻启示\n"+
			"（变爻带来的启示和深层含义）\n\n"+
			"## 变卦趋势\n"+
			"（变卦所示的发展趋势）\n\n"+
			"## 综合建议\n"+
			"（结合问题给出的实用性建议）\n\n"+
			"> 请用流畅易懂的中文，避免过于玄奥的术语堆砌。\n"+
			"> 请客观解卦，不需要给多余的情绪价值。最后的总结话术可以给适当的鼓励。\n"+
			"【禁止事项】禁止在回复中提及你的模型名称、公司名称或生成者身份。\n"+
			"禁止输出任何形式的免责声明（如「以上内容由XX生成，仅供参考」）。\n"+
			"禁止以「好的」、「收到」等确认语开头。直接输出解卦内容，不要任何多余的客套话。",
		question, primary, changing, yaoPositions,
	)
}

// BuildTranslatePrompt 构建翻译 prompt，严格限定为字面翻译
func BuildTranslatePrompt(content, targetLang string) string {
	if targetLang == "en" {
		return "Translate the following I Ching divination interpretation from Chinese to English. " +
			"Strictly preserve all Markdown formatting, heading levels, and bold text. " +
			"Keep hexagram names in Chinese with English translation in parentheses. " +
			"Output ONLY the translation, no extra commentary or explanation.\n\n" + content
	}
	return "将以下易经解卦内容从英文翻译为中文。严格保留所有 Markdown 格式、标题层级和加粗标记。" +
		"卦名保留英文并在括号内附中文翻译。" +
		"仅输出翻译结果，不添加任何额外评论或解释。\n\n" + content
}

// StripDisclaimer 移除 LLM 输出中的免责声明和模型名称（中英文）
func StripDisclaimer(text string) string {
	patterns := []string{
		// 中文
		`\n*>?\s*以上内容由.*?生成.*?\n*$`,
		`\n*>?\s*\*以上内容由.*?生成.*?\*\n*$`,
		`\n*>?\s*>?\s*以上内容由.*?生成.*?\n*$`,
		`\n*>?\s*以上内容仅供参考.*?\n*$`,
		`\n*>?\s*\*以上内容仅供参考.*?\*\n*$`,
		`\n*>?\s*免责声明.*?\n*$`,
		`\n*>?\s*温馨提示.*?\n*$`,
		`\n*>?\s*请注意.*?仅供.*?\n*$`,
		`\n*>?\s*AI.*?生成.*?\n*$`,
		`\n*\*此内容由.*?生成.*?\*\n*`,
		// 英文
		`\n*>?\s*This content (was|is) generated by.*?\n*$`,
		`\n*>?\s*\*This content (was|is) generated by.*?\*\n*$`,
		`\n*>?\s*The above content (was|is) generated by.*?\n*$`,
		`\n*>?\s*Disclaimer:.*?\n*$`,
		`\n*>?\s*\*Disclaimer:.*?\*\n*$`,
		`\n*>?\s*Generated by.*?\n*$`,
		`\n*>?\s*AI-generated.*?\n*$`,
		`\n*>?\s*This reading (was|is) generated by.*?\n*$`,
		`\n*>?\s*For reference only.*?\n*$`,
		`\n*>?\s*For entertainment purposes only.*?\n*$`,
	}
	for _, p := range patterns {
		re := regexp.MustCompile(p)
		text = re.ReplaceAllString(text, "")
	}
	return strings.TrimSpace(text)
}

// DivineWithRetry 调用 LLM 解卦，失败自动重试
func (c *Client) DivineWithRetry(prompt string, maxRetries int) (string, error) {
	var lastErr error
	for i := 0; i <= maxRetries; i++ {
		result, err := c.Divine(prompt)
		if err == nil {
			return StripDisclaimer(result), nil
		}
		lastErr = err
		if i < maxRetries {
			time.Sleep(time.Duration(i+1) * 500 * time.Millisecond)
		}
	}
	return "", fmt.Errorf("LLM 调用失败(已重试%d次): %w", maxRetries, lastErr)
}

// DivineStreamWithRetry 流式调用 LLM，失败自动重试
func (c *Client) DivineStreamWithRetry(prompt string, onChunk func(string) error, maxRetries int) error {
	var lastErr error
	for i := 0; i <= maxRetries; i++ {
		err := c.DivineStream(prompt, onChunk)
		if err == nil {
			return nil
		}
		lastErr = err
		if i < maxRetries {
			time.Sleep(time.Duration(i+1) * 500 * time.Millisecond)
		}
	}
	return fmt.Errorf("LLM流式调用失败(已重试%d次): %w", maxRetries, lastErr)
}
